from collections import deque  # simple FIFO queue for events
from dataclasses import dataclass  # lightweight event containers
from pathlib import Path  # filesystem paths for macro and figure output

from pprint import pprint  # pretty printing of metric dictionaries
import numpy as np  # numerical arrays
import pandas as pd  # tabular time-series structures
import matplotlib.pyplot as plt  # plotting library for figures

"""
Python & AI for Algorithmic Trading
Chapter 11 -- Event-Based Backtesting Framework

(c) Dr. Yves J. Hilpisch | The Python Quants GmbH
AI-powered by GPT 5.1 | https://linktr.ee/dyjh

Event-based SMA crossover backtest on daily data.

This script implements a minimal event-based backtesting framework
around a classic moving-average crossover strategy. It mirrors the
vectorised SMA example from Chapter 7 but expresses the logic in terms
of events, handlers, and an explicit event loop.

The components are:

* DataHandler --- streams end-of-day market data as MarketEvent
  objects.
* Strategy --- consumes MarketEvent instances and emits SignalEvent
  objects when the SMA rule changes state.
* Portfolio --- receives SignalEvent instances, generates OrderEvent
  instructions, and updates positions when FillEvent objects arrive.
* ExecutionHandler --- turns orders into instantaneous fills at the
  close price, modelling proportional transaction costs.

After simulation, the script computes daily net returns from the
event-driven positions, compares them with a vectorised buy-and-hold
benchmark, and exports LaTeX macros and an equity-curve figure for
Chapter 11.
"""

from ch05_eod_engineering import load_eod_panel  # static EOD price panel
from ch07_baseline_strategies import (  # backtest helpers
    backtest_strategy,
    compute_metrics,
    build_positions_buy_and_hold,
)

plt.style.use("seaborn-v0_8")  # consistent plotting style across figures


@dataclass
class MarketEvent:
    """Market data update for a single symbol and day."""

    time: pd.Timestamp
    price: float


@dataclass
class SignalEvent:
    """Trading signal generated by a strategy."""

    time: pd.Timestamp
    signal: float  # -1 short, 0 flat, +1 long


@dataclass
class OrderEvent:
    """Order to adjust position to a target signal."""

    time: pd.Timestamp
    target_position: float


@dataclass
class FillEvent:
    """Fill confirming execution at a given price."""

    time: pd.Timestamp
    position: float
    price: float


class EventQueue:
    """FIFO queue for events in the backtest."""

    def __init__(self) -> None:
        self._queue: deque=deque()

    def put(self, event: object) -> None:
        """Append a new event to the queue."""
        self._queue.append(event)

    def get(self) -> object | None:
        """Pop the next event or return None if the queue is empty."""
        if self._queue:
            return self._queue.popleft()
        return None

    def empty(self) -> bool:
        """Return True when there are no more events."""
        return not self._queue


class HistoricalDataHandler:
    """Stream daily close prices as MarketEvent instances."""

    def __init__(
        self,
        symbol: str="EURUSD",
        start: str | None=None,
        end: str | None=None,
    ) -> None:
        self.symbol = symbol
        panel = load_eod_panel().astype(float)
        prices = panel[self.symbol].dropna()

        start_ts = pd.to_datetime(start) if start is not None else None
        end_ts = pd.to_datetime(end) if end is not None else None
        if start_ts is not None or end_ts is not None:
            prices = prices.loc[start_ts:end_ts]

        self.prices = prices
        self.index = self.prices.index
        self.pointer = 0

    def have_more_bars(self) -> bool:
        """True while there are bars left to stream."""
        return self.pointer < len(self.index)

    def stream_next(self, events: EventQueue) -> None:
        """Push the next MarketEvent to the event queue."""
        if not self.have_more_bars():
            return
        ts = self.index[self.pointer]
        price = float(self.prices.iloc[self.pointer])
        events.put(MarketEvent(time=ts, price=price))
        self.pointer += 1


class SmaCrossStrategy:
    """Simple moving-average crossover strategy."""

    def __init__(
        self,
        fast_window: int=20,
        slow_window: int=100,
    ) -> None:
        self.fast_window = fast_window
        self.slow_window = slow_window
        self.prices: list[float]=[]
        self.times: list[pd.Timestamp]=[]
        self.current_signal: float=0.0

    def on_market_event(
        self,
        event: MarketEvent,
        events: EventQueue,
    ) -> None:
        """Update rolling averages and emit signals when they cross."""
        self.times.append(event.time)
        self.prices.append(event.price)
        series = pd.Series(self.prices, index=self.times)

        fast = series.rolling(self.fast_window).mean()
        slow = series.rolling(self.slow_window).mean()

        if len(series) < self.slow_window:
            return  # not enough data yet

        if fast.iloc[-1] > slow.iloc[-1] and self.current_signal <= 0.0:
            self.current_signal = 1.0
            events.put(
                SignalEvent(
                    time=event.time,
                    signal=self.current_signal,
                )
            )
        elif fast.iloc[-1] < slow.iloc[-1] and self.current_signal >= 0.0:
            self.current_signal = -1.0
            events.put(
                SignalEvent(
                    time=event.time,
                    signal=self.current_signal,
                )
            )


class NaivePortfolio:
    """Track positions and convert signals into fills."""

    def __init__(self) -> None:
        self.position: float=0.0  # current position in units of capital
        self.positions: list[float]=[]
        self.times: list[pd.Timestamp]=[]

    def on_signal(
        self,
        event: SignalEvent,
        events: EventQueue,
    ) -> None:
        """Create an order that moves to the target signal."""
        events.put(
            OrderEvent(
                time=event.time,
                target_position=event.signal,
            )
        )

    def on_fill(self, event: FillEvent) -> None:
        """Update internal position records from a fill."""
        self.position = event.position
        self.times.append(event.time)
        self.positions.append(self.position)

    def get_position_series(self) -> pd.Series:
        """Return the full position series indexed by time."""
        return pd.Series(self.positions, index=self.times)


class SimulatedExecutionHandler:
    """Turn orders into immediate fills at the closing price."""

    def __init__(self) -> None:
        self.last_price: float | None=None

    def on_market_event(self, event: MarketEvent) -> None:
        """Record the most recent price for use in fills."""
        self.last_price = event.price

    def on_order(
        self,
        event: OrderEvent,
        events: EventQueue,
    ) -> None:
        """Generate a fill at the latest known price."""
        if self.last_price is None:
            return
        events.put(
            FillEvent(
                time=event.time,
                position=event.target_position,
                price=self.last_price,
            )
        )


def format_pct(value: float) -> str:
    """Format a decimal fraction as a percentage string."""
    return f"{value * 100.0: .2f}\\%"  # percentage with two decimals


def format_float(value: float, decimals: int=2) -> str:
    """Format a floating-point number with fixed decimals."""
    fmt = f"{{: .{decimals}f}}"
    return fmt.format(value)


def write_tex_macros(
    metrics_bh: dict[str, float],
    metrics_sma: dict[str, float],
    trades_bh: int,
    trades_sma: int,
    symbol: str,
    fast_window: int,
    slow_window: int,
    cost_rate: float,
    fin_rate: float,
    leverage: float,
    start_date: str,
    end_date: str,
    outfile: str="figures/ch11_event_stats.tex",
) -> None:
    """Write LaTeX macros with event-based vs buy-and-hold statistics."""
    lines: list[str]=[]

    lines.append(
        "\\newcommand{\\chElevenBhFinalWealth}{"
        f"{format_float(metrics_bh['final_wealth'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaFinalWealth}{"
        f"{format_float(metrics_sma['final_wealth'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenBhAnnReturn}{"
        f"{format_pct(metrics_bh['ann_return'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaAnnReturn}{"
        f"{format_pct(metrics_sma['ann_return'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenBhAnnVol}{"
        f"{format_pct(metrics_bh['ann_vol'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaAnnVol}{"
        f"{format_pct(metrics_sma['ann_vol'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenBhSharpe}{"
        f"{format_float(metrics_bh['sharpe'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaSharpe}{"
        f"{format_float(metrics_sma['sharpe'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenBhMaxDD}{"
        f"{format_pct(metrics_bh['max_drawdown'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaMaxDD}{"
        f"{format_pct(metrics_sma['max_drawdown'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenBhHitRatio}{"
        f"{format_pct(metrics_bh['hit_ratio'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaHitRatio}{"
        f"{format_pct(metrics_sma['hit_ratio'])}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenBhNumTrades}{"
        f"{trades_bh}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSmaNumTrades}{"
        f"{trades_sma}"
        "}\n"
    )

    lines.append(
        "\\newcommand{\\chElevenSymbol}{"
        f"{symbol}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenFastWindow}{"
        f"{fast_window}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenSlowWindow}{"
        f"{slow_window}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenCostRate}{"
        f"{format_float(cost_rate, decimals=5)}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenFinRate}{"
        f"{format_float(fin_rate, decimals=5)}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenLeverage}{"
        f"{format_float(leverage, decimals=1)}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenStartDate}{"
        f"{start_date}"
        "}\n"
    )
    lines.append(
        "\\newcommand{\\chElevenEndDate}{"
        f"{end_date}"
        "}\n"
    )

    Path(outfile).write_text("".join(lines), encoding="utf8")


def plot_equity_curves(
    net_bh: pd.Series,
    net_sma: pd.Series,
    symbol: str,
    outfile: str="figures/ch11_event_sma_vs_bh.pdf",
) -> None:
    """Plot equity curves for buy-and-hold and event-based SMA."""
    wealth_bh = (1.0 + net_bh).cumprod()
    wealth_sma = (1.0 + net_sma).cumprod()

    wealth_bh = wealth_bh / wealth_bh.iloc[0]
    wealth_sma = wealth_sma / wealth_sma.iloc[0]

    fig, ax = plt.subplots(figsize=(7.0, 3.2))
    cmap = plt.cm.coolwarm

    w_min = float(min(wealth_bh.min(), wealth_sma.min()))
    w_max = float(max(wealth_bh.max(), wealth_sma.max()))
    padding = 0.05 * (w_max - w_min) if w_max > w_min else 0.02

    ax.plot(
        wealth_bh.index,
        wealth_bh.values,
        label=f"buy-and-hold ({symbol})",
        color=cmap(0.10),
        lw=1.0,
        ls=":",
    )
    ax.plot(
        wealth_sma.index,
        wealth_sma.values,
        label="event-based SMA strategy",
        color=cmap(0.90),
        lw=1.0,
    )

    ax.set_ylabel("wealth (normalised)")
    ax.set_xlabel("date")
    ax.set_title(f"{symbol}: event-based SMA vs buy-and-hold")
    ax.legend(loc="upper left")
    ax.set_ylim(
        max(0.0, w_min - padding),
        w_max + padding,
    )
    ax.grid(True, alpha=0.3)

    fig.tight_layout()
    fig.savefig(outfile, bbox_inches="tight")
    plt.close(fig)


def count_trades(position: pd.Series) -> int:
    """Count the number of trades implied by a position series."""
    pos = position.fillna(0.0)
    delta_q = pos.diff().fillna(pos)
    return int((delta_q != 0.0).sum())


def main(
    symbol: str="EURUSD",
    fast_window: int=20,
    slow_window: int=100,
    cost: float=0.0005,
    fin: float=0.0001,
    leverage: float=1.0,
    start: str | None=None,
    end: str | None=None,
) -> None:
    """Run event-based SMA backtest and create figures and macros."""
    events = EventQueue()
    data_handler = HistoricalDataHandler(
        symbol=symbol,
        start=start,
        end=end,
    )
    strategy = SmaCrossStrategy(
        fast_window=fast_window,
        slow_window=slow_window,
    )
    portfolio = NaivePortfolio()
    execution = SimulatedExecutionHandler()

    while True:
        if not events.empty():
            event = events.get()
            if isinstance(event, MarketEvent):
                execution.on_market_event(event)
                strategy.on_market_event(event, events)
            elif isinstance(event, SignalEvent):
                portfolio.on_signal(event, events)
            elif isinstance(event, OrderEvent):
                execution.on_order(event, events)
            elif isinstance(event, FillEvent):
                portfolio.on_fill(event)
        else:
            if data_handler.have_more_bars():
                data_handler.stream_next(events)
            else:
                break

    pos_sma_raw = portfolio.get_position_series()
    prices = data_handler.prices

    # Align event-based positions with the full daily price index and
    # carry forward the last filled position between fills so that
    # returns are computed over actual trading days rather than only on
    # trade dates.
    pos_sma = (
        pos_sma_raw.reindex(prices.index).ffill().fillna(0.0)
    )
    pos_sma = leverage * pos_sma  # apply leverage only to SMA strategy

    pos_bh = build_positions_buy_and_hold(prices)

    trades_bh = count_trades(pos_bh)
    trades_sma = count_trades(pos_sma)

    net_bh = backtest_strategy(
        prices,
        pos_bh,
        cost_rate=cost,
        fin_rate=fin,
    )
    net_sma = backtest_strategy(
        prices,
        pos_sma,
        cost_rate=cost,
        fin_rate=fin,
    )

    # For a fair visual and statistical comparison, restrict both
    # strategies to the period where the SMA rule can actually trade,
    # that is from the first non-zero position onwards.
    first_active = pos_sma[pos_sma != 0.0].index.min()
    if first_active is None:
        first_active = prices.index[0]
    net_bh = net_bh.loc[first_active:]
    net_sma = net_sma.loc[first_active:]

    metrics_bh = compute_metrics(net_bh)
    metrics_sma = compute_metrics(net_sma)

    start_date = first_active.date().isoformat()
    end_date = prices.index[-1].date().isoformat()

    write_tex_macros(
        metrics_bh,
        metrics_sma,
        trades_bh,
        trades_sma,
        symbol,
        fast_window,
        slow_window,
        cost,
        fin,
        leverage,
        start_date,
        end_date,
    )

    plot_equity_curves(net_bh, net_sma, symbol)

    print(f"{symbol} event-based SMA backtest metrics:")
    print("buy-and-hold:")
    pprint(metrics_bh)
    print("event-based SMA strategy:")
    pprint(metrics_sma)


if __name__ == "__main__":
    import argparse  # command-line argument parsing

    parser = argparse.ArgumentParser(
        description=(
            "Event-based SMA crossover backtest for a single symbol."
        ),
    )
    parser.add_argument(
        "--symbol",
        type=str,
        default="EURUSD",
        help="symbol to backtest (default: EURUSD)",
    )
    parser.add_argument(
        "--fast",
        type=int,
        default=20,
        help="fast SMA window in trading days (default: 20)",
    )
    parser.add_argument(
        "--slow",
        type=int,
        default=100,
        help="slow SMA window in trading days (default: 100)",
    )
    parser.add_argument(
        "--cost",
        type=float,
        default=0.0001,
        help="transaction-cost rate per unit turnover (default: 0.0001)",
    )
    parser.add_argument(
        "--fin",
        type=float,
        default=0.00001,
        help="daily financing rate on absolute position (default: 0.00001)",
    )
    parser.add_argument(
        "--leverage",
        type=float,
        default=1.0,
        help="leverage factor applied to the SMA strategy (default: 1.0)",
    )
    parser.add_argument(
        "--start",
        type=str,
        default=None,
        help='optional start date for the sample, for example "2020-01-01"',
    )
    parser.add_argument(
        "--end",
        type=str,
        default=None,
        help='optional end date for the sample, for example "2025-01-01"',
    )

    args = parser.parse_args()
    main(
        symbol=args.symbol,
        fast_window=args.fast,
        slow_window=args.slow,
        cost=args.cost,
        fin=args.fin,
        leverage=args.leverage,
        start=args.start,
        end=args.end,
    )
